### ISSUE TITLE
css style option no longer work

### ISSUE THREAD

**Issue by eddysteurs** [thomasloven/lovelace-badge-card#17]
since a few days the style commando's do no longer work for the badge card, all backgrounds remain grey  

example
- entity: binary_sensor.aqara_hub
    name: Aqara
    style: >
      :host { --label-badge-background-color: {% if
      is_state('binary_sensor.aqara_hub', 'on') %} lightgreen {% else %} red {%
      endif %}; }

**Comment by ildar170975** [comment]
1.  Never ever post an unformatted code. Impossible to analyze. Compare your post with other ones with a code. 
2. You seem to upgrade card-mod to at least 3.4.0 without reading release notes. Read it, it has info about a breaking change.

**Comment by eddysteurs** [comment]
added card_mod:
