### ISSUE TITLE
Controlling color?

### ISSUE THREAD

**Issue by scstraus** [thomasloven/lovelace-badge-card#2]
Hey, badge card is a great idea which is long overdue. I probably would have used badges with conditionals rather than glance cards much more extensively if this had been available previously. Now I'm trying to decide between it and big number card for my numeric statuses.. 

One major advantage big number card has is the conditional control over color. Is there any way to do this with badge card? 

I'm guessing you may already know that this is possible with card-mod hence have not added it here for that reason, could we do conditional color of the ring based on card-mod or is this a feature request?

**Comment by thomasloven** [comment]
You're right that card-mod is the way to go with this.
There are some excellent guides linked from the wiki in the card-mod repo which should get you started with colored badges. There's also some samples in the `test/` directory in the source.
