### ISSUE TITLE
How to add badges to masonry layout?

### ISSUE THREAD

**Issue by PrzemekSkw** [thomasloven/lovelace-badge-card#25]
Hello, I can add badges on other home assistant views but not on masonry. Is that possible?
Regards.

**Comment by ildar170975** [comment]
This is a repo for a badge-card.
It can be added everywhere.
If you are talking about badges which appear on a top of a view & which are not a card - this is not related to the badge-card & this repo.

**Comment by PrzemekSkw** [comment]
> This is a repo for a badge-card. It can be added everywhere. If you are talking about badges which appear on a top of a view & which are not a card - this is not related to the badge-card & this repo.

Hi, can You tell me how to add badge-card to  my masonry dashboard because when I add like in example I get error.

**Comment by PrzemekSkw** [comment]
I get empty card.
![image](https://github.com/user-attachments/assets/0c20f623-2838-455a-bcd0-8463bd581973)

**Comment by ildar170975** [comment]
This is wrong code. Open Readme, take the 1st example which contains 2 cards: Entities and badge-card, use the badge-card’s code.

**Comment by PrzemekSkw** [comment]
> This is wrong code. Open Readme, take the 1st example which contains 2 cards: Entities and badge-card, use the badge-card’s code.

When I try that I get error:
![Screenshot_2024-11-01-21-45-46-63_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/0067df89-9d02-46c3-8d26-ca31dca4fc8c)

**Comment by ildar170975** [comment]
1.  You have wrong indentation for the 1st line. 
2. The 1st line should not start with a hyphen.

**Comment by PrzemekSkw** [comment]
> 1. You have wrong indentation for the 1st line.
> 2. The 1st line should not start with a hyphen.

I try many options and always have some errors.
![Screenshot_2024-11-05-23-01-51-92_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/0509edc5-9af5-410d-a6cb-0ba9ccbdad9d)

**Comment by ildar170975** [comment]
This is a valid code:
```
type: custom:badge-card
badges:
  - entity: binary_sensor.updater
```
Google about a syntax of yaml.

**Comment by PrzemekSkw** [comment]
> This is a valid code:
> 
> ```
> type: custom:badge-card
> badges:
>   - entity: binary_sensor.updater
> ```
> 
> Google about a syntax of yaml.

Thank You very much. I'm almost sure I try that also 😐
Regards.
