### ISSUE TITLE
Small typo in example code

### ISSUE THREAD

**Issue by ngsmits** [thomasloven/lovelace-badge-card#4]
thanks for writing this great badge card. Really happy with it 👍 
While deploying it I've found a small typo in the last line of your entity filter sample code:

type: entity-filter
entities:
  - light.bed_light
  - light.ceiling_lights
  - light.kitchen_lights
state_filter:
  - "on"
card:
  type: badge-card

Should be:

type: entity-filter
entities:
  - light.bed_light
  - light.ceiling_lights
  - light.kitchen_lights
state_filter:
  - "on"
card:
  type: custom:badge-card

**Comment by thomasloven** [comment]
Fixed by #1
