### ISSUE TITLE
Use badge card as a replacement for badges

### ISSUE THREAD

**Issue by ruippeixotog** [thomasloven/lovelace-badge-card#5]
For a few months I have been looking for a way to bring back the only behavior I lost when moving from states UI to Lovelace: the ability to have one badge per device currently in the "Home" state in the top of the screen.

Lovelace badges are too restrictive to implement that and can't be extended as easily as cards, so I was evaluating the possibility of simulating badges with cards. I'm wrapping my head around the parts I need to make this happen: https://github.com/thomasloven/lovelace-auto-entities allows me to define the list of entities dynamically, while this project allows me to render badges as a normal card. However, the combination still follows the column-based layout for cards.

Is there a way for me to pin this badge card to the top of a view and have it be full-width?

**Comment by thomasloven** [comment]
If you activate panel mode on your view and make it's card a vertical stack, you can put the badge card at the top, and then all your other cards below it.

It's an old trick from The Man himself:
![image](https://user-images.githubusercontent.com/1299821/123797855-ea4e2680-d8e6-11eb-8445-c9a5f093f4fa.png)

My layout-card can give you more control too.
